whats-new/index.html
-adjusted the excess space for each card for News and Events pages
=> mobile responsiveness

properties/rcd-winterbreeze-homes-bulacan/index.html
added slash to permalink to link the winterbreeze-bulacan page
=> updated index

properties/Royale-Homes-Balayan-batangas/index.html, properties/Royale-Homes-Silang-Phase-4/index.html, properties/index.html, properties/rcd-bf-homes-paranaque/index.html, properties/rcd-winterbreeze-homes-bulacan/index.html, properties/rcd-winterbreeze-homes-cavite/index.html
-adjusted the "click here to know button" to make it clickable. Issue #193
-remove the carousel function an replace it with swiper function , applied for all of the properties. Issue #194
=> Property page

properties/Royale-Homes-Balayan-batangas/index.html, properties/Royale-Homes-Silang-Phase-4/index.html, properties/rcd-bf-homes-paranaque/index.html, properties/rcd-winterbreeze-homes-bulacan/index.html, properties/rcd-winterbreeze-homes-cavite/index.html
-Embedded the location from google map for all the properties  . Issue #205
-Embedded a YT a video for all of the properties . Issue #206
-Insert Floor plan for each property pages #207
=> Property page update

whats-new/index.html, whats-new/subpages-events/32nd-anniversary.html, whats-new/subpages-events/33rd-anniversary.html, whats-new/subpages-events/34th-anniversary.html, whats-new/subpages-events/moving-forward.html, whats-new/subpages-events/royalhomesbataan.html, whats-new/subpages-events/royalhomestuy.html
-updated the valid links for each events section
-removed the .html on the permalink
=> updated the links

index.html
-adjusted the size of each container into square
- changed the photo's responsiveness
=> adjusted the news and updates section

new-properties/index.html
-updated text for paragraphs to index.html
=> new-properties

_includes/footer.html, _includes/top-menu.html, _layouts/default.html, contacts/index.html, index.html
- Fixed 'Site Viewing Schedule' Section
- Added Demo AI Chatbot
- Contact Us Page Adjustments and Minor Fix
=> Main Page, AI Chatbot Demo, and Contact Us Update No. 2

assets/css/styles.css, new-ourproperties/index.html
-removed Swiper effect #276
-replaced "CLICK HERE TO KNOW MORE" button to "KNOW MORE"#277
-removed the Carousel #278
-added CSS to assets folder for new-ourproperties page
by Jalen
=> New-ourproperties -page index update

assets/css/styles.css, properties/index.html, properties/royale-homes-silang-cavite/index.html
-adjusted the prices
-adjust on HTML placing for the "KNOW MORE" button 
-adjusted the page for mobile responsiveness
-Jalen
=> updated CSS and HTML for properties page

properties/index.html, properties/royale-homes-mariveles-bataan/index.html, properties/royale-homes-norzagaray/index.html, properties/royale-homes-silang-cavite/index.html, properties/royale-homes-silang-phase4/index.html/index.html, properties/royale-homes-tuy-batangas/index.html, properties/royalehomes-balayan-batangas/index.html, properties/villas-de-bacoor-dulongbayan/index.html
-removed logos inside the Parallax image
=> updated index html for properties

properties/royale-homes-norzagaray/index.html, properties/villas-de-bacoor-dulongbayan/index.html, properties/villas-de-trece-martires-cavite/index.html
=> updated one property

properties/index.html, properties/rcd-bf-homes-paranaque/index.html, properties/rcd-winter-breeze-homes-bulacan/index.html, properties/rcd-winter-breeze-homes-cavite/index.html, properties/royale-homes-balayan-batangas/index.html, properties/royale-homes-mariveles-bataan/index.html, properties/royale-homes-norzagaray/index.html, properties/royale-homes-silang-phase3/index.html, properties/royale-homes-silang-phase4/index.html/index.html, properties/royale-homes-tuy-batangas/index.html, properties/villas-de-bacoor-dulongbayan/index.html, properties/villas-de-trece-martires-cavite/index.html
-updated the price for the properties
-added space for "quick summary" section
=> updated property index

house-catalogue/index.html
-added zoom effect for all pictures #429
-adjusted the buttons for all of the cards #423
- fixed the mobile responsiveness of the House -catalogue page -replaced "Reserve now" button into "Book a tripping" button
=> updated index/house-catalogue

index.html
- Major /index Button adjustment and spacing
=> Index Patch #418 #416 #413 #312 #354 #355 #356 #357 #416 #417 #418

properties/rcd-bf-homes-paranaque/index.html, properties/rcd-winter-breeze-homes-bulacan/index.html, properties/rcd-winter-breeze-homes-cavite/index.html, properties/royale-homes-balayan-batangas/index.html, properties/royale-homes-mariveles-bataan/index.html, properties/royale-homes-norzagaray/index.html, properties/royale-homes-silang-phase3/index.html, properties/royale-homes-silang-phase4/index.html, properties/royale-homes-tuy-batangas/index.html, properties/villas-de-bacoor-dulongbayan/index.html, properties/villas-de-trece-martires-cavite/index.html
-updated the color background of every property page
=> updated property page

_includes/footer.html, index.html
Double checking of old and current issues that are not linked to commits (assigned to ferenal only)
=> Old Issues Backlog Checking #164 #307 #442 #432 #413 #448

_layouts/default.html, _layouts/default2.html, index.html
Additional changes:
- /index buttons fixed
- "Book a Tripping" button redirected to sales@rcdland.com
=> Tawt.to Admin Account Changed #443 #461 #451 #448 #443 #442

properties/index.html, properties/rcd-winter-breeze-homes-bulacan/index.html, properties/rcd-winter-breeze-homes-cavite/index.html, properties/villas-de-bacoor-dulongbayan/index.html
-removed "Available house model for Winterbreeze Homes General Trias, Cavite , since it was already SOLD OUT #394
-removed "Available house model for Winterbreeze Homes San Jose Del Monte, Bulacan , since it was already SOLD OUT #393
-removed "Available house model for Villas De Bacoor Dulong Bayan, Cavite , since it was already SOLD OUT #392
-updated the SOLD UNITS in property. index.html
=> Properties update

_layouts/default.html, assets/css/styles.css, assets/js/scripts.js, contacts/index.html, index.html, walkthrough/daphne/bedroom-1.html, walkthrough/daphne/bedroom-2.html, walkthrough/daphne/dining-kitchen.html, walkthrough/daphne/groundfloor-stairs.html, walkthrough/daphne/hallway.html, walkthrough/daphne/index.html, walkthrough/th47/2f-stairs.html, walkthrough/th47/bedroom-1.html, walkthrough/th47/bedroom-2.html, walkthrough/th47/dining-kitchen.html, walkthrough/th47/groundfloor-stairs.html, walkthrough/th47/index.html
for a better format and readability of the code.
- Additional fix for Contacts Page Mobile View
=> Code Format Corrections #481

house-catalogue/Kylee/index.html, house-catalogue/bf-townhomes/index.html, house-catalogue/commercial-lot/index.html, house-catalogue/daphne/index.html, house-catalogue/index.html, house-catalogue/th36/index.html, house-catalogue/th47/index.html, house-catalogue/th65/index.html, house-catalogue/trece-commercial/index.html, properties/rcd-bf-homes-paranaque/index.html, properties/rcd-winter-breeze-homes-bulacan/index.html, properties/rcd-winter-breeze-homes-cavite/index.html, properties/royale-homes-balayan-batangas/index.html, properties/royale-homes-mariveles-bataan/index.html, properties/royale-homes-norzagaray/index.html, properties/royale-homes-silang-phase1-3/index.html, properties/royale-homes-silang-phase4/index.html, properties/royale-homes-tuy-batangas/index.html, properties/villas-de-bacoor-dulongbayan/index.html, properties/villas-de-trece-martires-cavite/index.html
#530
#531
#532
#533
#534
#535
#536
#537
#544
#546
#547
=> updates catalog and properties page
